package it.signflow.reports;

public enum ReportWorkflowOperation {
    ASSIGN_SIGNER,
    EVALUATE_READINESS,
    FIRST_PREVIEW,
    ADMIN_CORRECTION,
    REQUEST_REVIEW,
    VIEW_REVIEW_DOCUMENT,
    APPROVE_REVIEW,
    REJECT_REVIEW,
    RETURN_REVIEW,
    PREPARE_COUNTER_SIGNATURE
}
