package it.signflow.reports;

public enum ReportWorkflowOperation {
    PARSE_INGESTION,
    COMPLETE_INGESTION,
    ASSIGN_SIGNER,
    EVALUATE_READINESS,
    FIRST_PREVIEW,
    ADMIN_CORRECTION,
    REQUEST_REVIEW,
    VIEW_REVIEW_DOCUMENT,
    APPROVE_REVIEW,
    REJECT_REVIEW,
    RETURN_REVIEW,
    PREPARE_COUNTER_SIGNATURE,
    CREATE_SIGNATURE_BATCH,
    START_SIGNATURE,
    COMPLETE_MOCK_SIGNATURE,
    FAIL_MOCK_SIGNATURE,
    RETRY_MOCK_SIGNATURE,
    CANCEL_SIGNATURE_BATCH
}
